/*
 * De:
 * Ds:
 */
package co.edu.restaurante.interfaces;

/**
 *
 * @author Pipe
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        Desktop = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        PlatosMenu = new javax.swing.JMenu();
        MenuPlatosAgregar = new javax.swing.JMenuItem();
        MenuPlatoEditar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuEmpleadosAgregar = new javax.swing.JMenuItem();
        MenuEmpleadosEditar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuCargoAgregar = new javax.swing.JMenuItem();
        MenuCargoEditar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MenuMesaAgregar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Desktop.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        PlatosMenu.setText("Platos");

        MenuPlatosAgregar.setText("Agregar");
        MenuPlatosAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPlatosAgregarActionPerformed(evt);
            }
        });
        PlatosMenu.add(MenuPlatosAgregar);

        MenuPlatoEditar.setText("Editar");
        MenuPlatoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPlatoEditarActionPerformed(evt);
            }
        });
        PlatosMenu.add(MenuPlatoEditar);

        jMenuBar1.add(PlatosMenu);

        jMenu2.setText("Empleados");

        MenuEmpleadosAgregar.setText("Agregar");
        MenuEmpleadosAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmpleadosAgregarActionPerformed(evt);
            }
        });
        jMenu2.add(MenuEmpleadosAgregar);

        MenuEmpleadosEditar.setText("Editar");
        MenuEmpleadosEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmpleadosEditarActionPerformed(evt);
            }
        });
        jMenu2.add(MenuEmpleadosEditar);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Cargo");

        MenuCargoAgregar.setText("Agregar");
        MenuCargoAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCargoAgregarActionPerformed(evt);
            }
        });
        jMenu5.add(MenuCargoAgregar);

        MenuCargoEditar.setText("Editar");
        MenuCargoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCargoEditarActionPerformed(evt);
            }
        });
        jMenu5.add(MenuCargoEditar);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Mesa");

        MenuMesaAgregar.setText("Agregar");
        MenuMesaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMesaAgregarActionPerformed(evt);
            }
        });
        jMenu1.add(MenuMesaAgregar);

        jMenuItem2.setText("Editar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPlatosAgregarActionPerformed(java.awt.event.ActionEvent evt) {
        PlatosAddFr platosAdd = new PlatosAddFr();
        Desktop.add(platosAdd);
        platosAdd.show();
    }//GEN-LAST:event_MenuPlatosAgregarActionPerformed

    private void MenuCargoAgregarActionPerformed(java.awt.event.ActionEvent evt) {
        CargosAddFr cargoAdd = new CargosAddFr();
        Desktop.add(cargoAdd);
        cargoAdd.show();
    }//GEN-LAST:event_MenuCargoAgregarActionPerformed

    private void MenuEmpleadosAgregarActionPerformed(java.awt.event.ActionEvent evt) {
        EmpleadoAddFr empleadoAdd = new EmpleadoAddFr();
        Desktop.add(empleadoAdd);
        empleadoAdd.show();
    }//GEN-LAST:event_MenuEmpleadosAgregarActionPerformed

    private void MenuCargoEditarActionPerformed(java.awt.event.ActionEvent evt) {
        CargoEditFr cargoEdit = new CargoEditFr();
        Desktop.add(cargoEdit);
        cargoEdit.show();
    }//GEN-LAST:event_MenuCargoEditarActionPerformed

    private void MenuMesaAgregarActionPerformed(java.awt.event.ActionEvent evt) {
        MesaAddFr mesaAdd = new MesaAddFr();
        Desktop.add(mesaAdd);
        mesaAdd.show();
    }//GEN-LAST:event_MenuMesaAgregarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
        MesaEditFr mesaEdit = new MesaEditFr();
        Desktop.add(mesaEdit);
        mesaEdit.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MenuEmpleadosEditarActionPerformed(java.awt.event.ActionEvent evt) {
        EmpleadoEditFr empleadoEdit = new EmpleadoEditFr();
        Desktop.add(empleadoEdit);
        empleadoEdit.show();
    }//GEN-LAST:event_MenuEmpleadosEditarActionPerformed

    private void MenuPlatoEditarActionPerformed(java.awt.event.ActionEvent evt) {
        PlatosEditFr platoEdit = new PlatosEditFr();
        Desktop.add(platoEdit);
        platoEdit.show();
    }//GEN-LAST:event_MenuPlatoEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Desktop;
    private javax.swing.JMenuItem MenuCargoAgregar;
    private javax.swing.JMenuItem MenuCargoEditar;
    private javax.swing.JMenuItem MenuEmpleadosAgregar;
    private javax.swing.JMenuItem MenuEmpleadosEditar;
    private javax.swing.JMenuItem MenuMesaAgregar;
    private javax.swing.JMenuItem MenuPlatoEditar;
    private javax.swing.JMenuItem MenuPlatosAgregar;
    private javax.swing.JMenu PlatosMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
